@echo off
setlocal EnableDelayedExpansion
title FrameKraft — Setup Wizard
color 0A

echo.
echo  ==========================================
echo    FRAMEKRAFT — Automatic Setup Wizard
echo  ==========================================
echo.
echo  This script will:
echo    1. Check Node.js is installed
echo    2. Create your .env config file
echo    3. Install all npm packages
echo    4. Import the database into MySQL (XAMPP)
echo    5. Create the admin account
echo    6. Start the server
echo.
pause

:: ─── Step 1: Check Node.js ───────────────────────────────────────────────────
echo.
echo [1/6] Checking Node.js...
where node >nul 2>&1
if %ERRORLEVEL% NEQ 0 (
    echo.
    echo  ERROR: Node.js is NOT installed.
    echo  Please download and install it from: https://nodejs.org/
    echo  Choose the LTS version (18 or higher).
    echo.
    pause
    exit /b 1
)
for /f "tokens=*" %%i in ('node --version') do set NODE_VER=%%i
echo  Node.js found: %NODE_VER%  OK


:: ─── Step 2: Check MySQL (XAMPP) ─────────────────────────────────────────────
echo.
echo [2/6] Checking MySQL (XAMPP)...

:: Try common XAMPP locations
set MYSQL_PATH=
if exist "C:\xampp\mysql\bin\mysql.exe"     set MYSQL_PATH=C:\xampp\mysql\bin\mysql.exe
if exist "C:\XAMPP\mysql\bin\mysql.exe"     set MYSQL_PATH=C:\XAMPP\mysql\bin\mysql.exe
if exist "D:\xampp\mysql\bin\mysql.exe"     set MYSQL_PATH=D:\xampp\mysql\bin\mysql.exe
if exist "C:\xampp7\mysql\bin\mysql.exe"    set MYSQL_PATH=C:\xampp7\mysql\bin\mysql.exe

if "%MYSQL_PATH%"=="" (
    echo.
    echo  WARNING: MySQL not found at common XAMPP locations.
    echo  Make sure XAMPP is installed and MySQL is running.
    echo  Then manually run the SQL files from phpMyAdmin:
    echo    http://localhost/phpmyadmin
    echo.
    echo  SQL files to run (in order):
    echo    database\schema.sql
    echo    database\seed.sql
    echo.
    set SKIP_DB=1
) else (
    echo  MySQL found: %MYSQL_PATH%  OK
    set SKIP_DB=0
)


:: ─── Step 3: Create .env file ────────────────────────────────────────────────
echo.
echo [3/6] Creating .env configuration file...

if exist ".env" (
    echo  .env already exists — skipping creation.
    echo  To reset it, delete .env and re-run this script.
) else (
    :: Generate a random session secret
    set CHARS=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789
    set SECRET=
    for /L %%i in (1,1,32) do (
        set /A IDX=!RANDOM! %% 62
        for /F %%c in ('echo !CHARS!') do (
            set SECRET=!SECRET!!CHARS:~%%IDX,1!!
        )
    )
    :: Fallback secret if loop fails
    if "!SECRET!"=="" set SECRET=FrameKraft_Secret_%RANDOM%%RANDOM%

    (
        echo # FrameKraft Environment Configuration
        echo # Auto-generated by setup.bat
        echo.
        echo PORT=3000
        echo NODE_ENV=development
        echo.
        echo DB_HOST=localhost
        echo DB_PORT=3306
        echo DB_USER=root
        echo DB_PASSWORD=
        echo DB_NAME=framekraft_db
        echo.
        echo SESSION_SECRET=!SECRET!
        echo.
        echo ADMIN_EMAIL=admin@framekraft.com
        echo ADMIN_PASSWORD=Admin@123
        echo ADMIN_NAME=Store Admin
        echo.
        echo # Razorpay ^(add your keys when ready^)
        echo RAZORPAY_KEY_ID=rzp_test_XXXXXXXXXXXX
        echo RAZORPAY_KEY_SECRET=XXXXXXXXXXXXXXXXXXXXXXXX
        echo RAZORPAY_WEBHOOK_SECRET=your_webhook_secret_here
    ) > .env
    echo  .env file created  OK
)


:: ─── Step 4: Install npm packages ────────────────────────────────────────────
echo.
echo [4/6] Installing npm packages (this may take 1-2 minutes)...
call npm install --loglevel=error
if %ERRORLEVEL% NEQ 0 (
    echo  ERROR: npm install failed. Check your internet connection.
    pause
    exit /b 1
)
echo  npm packages installed  OK


:: ─── Step 5: Import database ─────────────────────────────────────────────────
echo.
echo [5/6] Setting up database...

if "%SKIP_DB%"=="1" (
    echo  Skipping automatic DB import ^(MySQL not found^).
    echo  Please import manually via phpMyAdmin — see instructions above.
) else (
    echo  Creating database and importing schema...
    "%MYSQL_PATH%" -u root -e "CREATE DATABASE IF NOT EXISTS framekraft_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" 2>nul
    if %ERRORLEVEL% NEQ 0 (
        echo  WARNING: Could not connect to MySQL. Is XAMPP MySQL running?
        echo  Start XAMPP Control Panel ^> Click START next to MySQL, then re-run.
        set SKIP_DB=1
    ) else (
        "%MYSQL_PATH%" -u root framekraft_db < database\schema.sql
        echo  Schema imported  OK
        "%MYSQL_PATH%" -u root framekraft_db < database\seed.sql
        echo  Sample data imported  OK
    )
)


:: ─── Step 6: Create admin account ────────────────────────────────────────────
echo.
echo [6/6] Creating admin account...

if "%SKIP_DB%"=="1" (
    echo  Skipping admin seed ^(database not set up yet^).
    echo  Run: npm run seed:admin  after the database is ready.
) else (
    call node scripts\seedAdmin.js
    if %ERRORLEVEL% NEQ 0 (
        echo  WARNING: Admin seed failed. Run manually: npm run seed:admin
    ) else (
        echo  Admin account created  OK
    )
)


:: ─── Done! ───────────────────────────────────────────────────────────────────
echo.
echo  ==========================================
echo    SETUP COMPLETE!
echo  ==========================================
echo.
echo  Admin login:
echo    Email:    admin@framekraft.com
echo    Password: Admin@123
echo.
echo  Starting server now...
echo  Open your browser to: http://localhost:3000
echo  Admin panel:          http://localhost:3000/admin/login
echo.
echo  Press Ctrl+C in this window to stop the server.
echo.
call npm run dev

pause
